version: "3.0"

services:
    beacon_node:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - ${LIGHTHOUSE_DATA}:/root/.lighthouse
            - ./scripts:/root/scripts:ro
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 5054:5054/tcp     # metrics endpoint
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
        restart: always
    validator_client:
        image: sigp/lighthouse:${LIGHTHOUSE_VERSION}
        volumes:
            - ${LIGHTHOUSE_DATA}:/root/.lighthouse
            - ./scripts:/root/scripts
            - ./validator_keys:/root/validator_keys
        depends_on:
            - beacon_node
        ports:
            - 5064:5064/tcp     # metrics endpoint
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
        restart: always
    besu:
        image: hyperledger/besu:${BESU_VERSION}
        entrypoint: bash
        volumes:
            - ${BESU_DATA}:/var/lib/besu
            - ./scripts:/opt/besu/scripts
        command: scripts/start-besu.sh
        ports:
            - '8545:8545'
            - '30303:30303'
