version: "3.0"

services:
    beacon_node:
        image: sigp/lighthouse:latest
        volumes:
            - ${LIGHTHOUSE_DATA}:/root/.lighthouse
            - ./scripts:/root/scripts
        ports:
            - 5052:5052/tcp
            - 5053:5053/tcp
            - 5054:5054/tcp     # metrics endpoint
            - 9000:9000/tcp
            - 9000:9000/udp
        env_file: .env
        command: sh /root/scripts/start-beacon-node.sh
        restart: on-failure
    validator_client:
        image: sigp/lighthouse:latest
        volumes:
            - ${LIGHTHOUSE_DATA}:/root/.lighthouse
            - ./scripts:/root/scripts
            - ./validator_keys:/root/validator_keys
        depends_on:
            - beacon_node
        env_file: .env
        command: sh /root/scripts/start-validator-client.sh
        restart: on-failure
    geth:
        image: ethereum/client-go
        entrypoint: /bin/sh
        volumes:
            - ${GETH_DATA}:/root/.ethereum
            - ./scripts:/root/scripts
        ports:
            - 30303:30303/tcp
            - 30303:30303/udp
        env_file: .env
        command: /root/scripts/start-geth.sh
        restart: on-failure
    eth1-provider:
        image: nginx:1.19-alpine
        container_name: nginx
        restart: always
        expose:
            - "8545/tcp"
        volumes:
            - ./eth1-provider/nginx.conf:/etc/nginx/nginx.conf:ro
